image: docker:latest

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_SHORT_SHA}
  CONTAINER_IMAGE_LATEST: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  CONTAINER_IMAGE_TAG: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}
  EXT_REG_IMG: ${EXT_REG_REGISTRY}/${EXT_REG_ORGANISATION}/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
  EXT_REG_IMG_LATEST: ${EXT_REG_REGISTRY}/${EXT_REG_ORGANISATION}/${CI_PROJECT_NAME}:latest
  EXT_REG_IMG_TAG: ${EXT_REG_REGISTRY}/${EXT_REG_ORGANISATION}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}

stages:
  - release

release-tag:
  stage: release
  services:
   - docker:dind
  script:
    - export DOCKER_HOST=tcp://docker:2375/
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build --pull -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAG}
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAG}
    - docker push ${CONTAINER_IMAGE_LATEST}
    - docker login -u ${EXT_REG_USER} -p ${EXT_REG_PASSWORD} ${EXT_REG_REGISTRY}
    - docker tag ${CONTAINER_IMAGE} ${EXT_REG_IMG}
    - docker tag ${CONTAINER_IMAGE} ${EXT_REG_IMG_LATEST}
    - docker tag ${CONTAINER_IMAGE} ${EXT_REG_IMG_TAG}
    - docker push ${EXT_REG_IMG}
    - docker push ${EXT_REG_IMG_LATEST}
    - docker push ${EXT_REG_IMG_TAG}
  only:
    - tags
